commands:
  no-permission: '&cYou don''t have permission to do that!'
  not-player: '&cYou must be a player to do that!'
  help: |
    &5&lAnnunaki AntiCheat
    &7- &d/annunaki alerts
    &7- &d/annunaki banwave
    &7- &d/annunaki debug
    &7- &d/annunaki reload
    &7- &d/annunaki settings
  alerts-enabled: '&aAlerts are now enabled!'
  alerts-disabled: '&cAlerts are now disabled!'

checks:
  alert: '&5Annunaki &7// &d%player% &7failed &d%name% (%type%)%experimental% &5x%vl%'
  hover: |
    &7%description%

    &7Info: &d%info%
    &7TPS: &d%tps%
    &7Ping: &d%ping%
    &7Version: &d%version%
  click-command: '/tp %player%'
  # Set to true to disable punishments, setbacks and kicks.
  silent: false

banwave:
  enabled: true
  interval: 6h
  ban:
    delay-ticks: 20
    commands:
       - "kick %player% Unfair Advantage"
       - "broadcast &d%player% &rwas banned for an &dUnfair Advantage"
  broadcast:
    enabled: true
    start: "\n &dBanwave started! \n"
    end: "\n &dBanwave ended, banning &r%players% &dplayers! \n"
  command:
    started: "&dBanwave has been started!"
    already-running: "&dA banwave is already running"
    stopped: "&dBanwave has been stopped!"
    not-running: "&dNo banwave is running."
